using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoreAI.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddArticleSourceKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "SourceId",
                table: "Articles",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "SourceType",
                table: "Articles",
                type: "text",
                nullable: false,
                defaultValue: "");

            // Toutes les lignes existantes proviennent de Raindrop (seule source ingérée avant le lot 8,
            // #49) : SourceId reprend l'id Raindrop numérique déjà porté par Id, converti en texte. Doit
            // précéder la création de l'index unique ci-dessous, sans quoi toutes les lignes partageraient
            // temporairement (SourceType, SourceId) = ('', '').
            migrationBuilder.Sql(
                "UPDATE \"Articles\" SET \"SourceType\" = 'Raindrop', \"SourceId\" = \"Id\"::text;");

#pragma warning disable CA1861 // code de migration généré, appelé une seule fois par déploiement
            migrationBuilder.CreateIndex(
                name: "IX_Articles_SourceType_SourceId",
                table: "Articles",
                columns: new[] { "SourceType", "SourceId" },
                unique: true);
#pragma warning restore CA1861

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "Articles",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint")
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            // La séquence d'identité créée par ADD GENERATED BY DEFAULT AS IDENTITY démarre à 1 : sans ce
            // redémarrage, le prochain INSERT généré par la base entrerait en collision avec les lignes
            // existantes, dont Id porte déjà l'ancien id Raindrop numérique (potentiellement très
            // supérieur à 1).
            migrationBuilder.Sql(
                "SELECT setval(pg_get_serial_sequence('\"Articles\"', 'Id'), COALESCE((SELECT MAX(\"Id\") FROM \"Articles\"), 0) + 1, false);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "Articles",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.DropIndex(
                name: "IX_Articles_SourceType_SourceId",
                table: "Articles");

            migrationBuilder.DropColumn(
                name: "SourceId",
                table: "Articles");

            migrationBuilder.DropColumn(
                name: "SourceType",
                table: "Articles");
        }
    }
}
