// <auto-generated />
using System;
using LoreAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoreAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoreAiDbContext))]
    [Migration("20260823151617_AddLibraryIndexing")]
    partial class AddLibraryIndexing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.ArticleEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClassificationModel")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationRawResponse")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ClassifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DiscordNotifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EmailDigestSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Moved")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("OriginalTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedCollection")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SuggestedTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("WriteBackAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WriteBackStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("EmailDigestSentAtUtc");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.CycleRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSeen")
                        .HasColumnType("integer");

                    b.Property<int>("Moved")
                        .HasColumnType("integer");

                    b.Property<int>("Notified")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TagsApplied")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedUtc");

                    b.ToTable("CycleRuns");
                });

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.LibraryIndexStateEntity", b =>
                {
                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastFullPassCompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastFullPassStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResumePage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceType");

                    b.ToTable("LibraryIndexStates");
                });

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.LibraryItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Broken")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cover")
                        .HasColumnType("text");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text");

                    b.Property<string>("HighlightsJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Important")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RaindropCollectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Origin");

                    b.ToTable("LibraryItems");
                });

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.PollingStateEntity", b =>
                {
                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSourceItemId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceType");

                    b.ToTable("PollingStates");
                });
#pragma warning restore 612, 618
        }
    }
}
