// <auto-generated />
using System;
using LoreAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoreAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoreAiDbContext))]
    [Migration("20260822220936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.ArticleEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClassificationModel")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationRawResponse")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ClassifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DiscordNotifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EmailDigestSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Moved")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("OriginalTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RaindropCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RaindropLastUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RaindropType")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedCollection")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SuggestedTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("WriteBackAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WriteBackStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailDigestSentAtUtc");

                    b.HasIndex("RaindropCreatedUtc");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("LoreAI.Infrastructure.Persistence.PollingStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastRaindropId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PollingStates", t =>
                        {
                            t.HasCheckConstraint("CK_PollingState_SingleRow", "\"Id\" = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
