<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RaindropAI.Worker-09f11de5-4c4a-41d2-96e9-2e40e4d0111c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Coravel" Version="6.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaindropAI.Core\RaindropAI.Core.csproj" />
    <ProjectReference Include="..\RaindropAI.Infrastructure\RaindropAI.Infrastructure.csproj" />
  </ItemGroup>
</Project>
