<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RaindropAI.Worker-09f11de5-4c4a-41d2-96e9-2e40e4d0111c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Coravel" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaindropAI.Core\RaindropAI.Core.csproj" />
    <ProjectReference Include="..\RaindropAI.Infrastructure\RaindropAI.Infrastructure.csproj" />
  </ItemGroup>
</Project>
